# Appium Server Settings
appium.url=http://127.0.0.1:4723

# Device Settings
platform.name=Android
device.name=emulator-5554
automation.name=UiAutomator2

# App Settings
app.path=APK_IPA/app-flavorInternal-debug.apk
app.package=jio.cloud.drive
app.activity=com.rjil.cloud.tej.client.app.AppStartActivity

# Timeouts
implicit.wait=10
explicit.wait=20
